### ISSUE TITLE
ロゴ

### ISSUE THREAD

**Issue by tsubasa-sris** [shizunaito/byblos#14]
やはり、あの可愛いフクロウは一旦お蔵に入って頂こうかな、、という気持ちになりました🦉
こういうロゴどうですか？案（色は仮、コピーはいいのが思いついたら教えていただきたい..!）

フクロウのまん丸の目をモチーフにしました。
![byblos-logo](https://user-images.githubusercontent.com/21121644/41241526-1c3077de-6dd8-11e8-8b59-ab1a15af57ba.png)

ラコステのポジションも狙える
![image](https://user-images.githubusercontent.com/21121644/41285360-da36b664-6e76-11e8-8fce-567901356709.png)

バリエーション展開
![byblos-pattern](https://user-images.githubusercontent.com/21121644/41286571-e8501ff2-6e7a-11e8-9f8e-8ea634ce3c82.png)

**Comment by shizunaito** [comment]
お…お蔵入り…悲しい 😭 悲しいのでせめて思い出としてissueに貼ってくれませんか 😭 

でも新しいフクロウもかわいいです！いいと思います！！
個人的にはカラーのやつ目が愛くるしくて好きです 🙋 

ロゴは **案２** が初見バランスが良さそうに見えました 👀 

リリースと同時にSUZURIでグッズ出したいくらいいいですね！ 👕

**Comment by tsubasa-sris** [comment]
ちょっと初代はイラスト感が強すぎて汎用性にかけるかも,,,と思い、リリースもしてないのに2代目フクロウを生み出してしまいました。。。🦉

初代はこちらです
![byblos-old](https://user-images.githubusercontent.com/21121644/41355423-76242ff8-6f5c-11e8-9cfa-cd57c8e61802.png)

これでどうでしょうか！
![byblos-eyecatch](https://user-images.githubusercontent.com/21121644/41606099-e0316fe4-741d-11e8-908e-8faeba38a3fe.png)

**Comment by shizunaito** [comment]
いいと思います〜 🙆 わかりやすくなった！！！

**Comment by tsubasa-sris** [comment]
完成〜〜〜〜🦉
